### ISSUE TITLE
Can't load manga from 'Merged Source'

### ISSUE THREAD

**Issue by holysnipz** [CarlosEsco/Neko#456]
Look like Neko needs new workaround for their "[anti-hotlinking](https://support.cloudflare.com/hc/en-us/articles/200170026-What-does-enabling-Cloudflare-Hotlink-Protection-do-)"?

### Device information
* Tachiyomi version: 2.2.2.1

## Steps to reproduce
1. Find manga with mergeable chapters (for my case: [Übel Blatt](https://mangadex.org/title/1459))
2. Merge with M4L *(the only alternative source Neko provide)*
3. Trying to read Merged Chapters

### Expected behavior
The manga should be loaded fine, like reading from their site
![image](https://user-images.githubusercontent.com/9103583/110780896-cdd6a180-8297-11eb-8824-bfa357f222c5.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/9103583/110780807-b1d30000-8297-11eb-9ee3-b4ed9fe910f1.png)

### Other details
 - Tried with DoH On/Off
 - [log](https://gist.github.com/holysnipz/0fe4c8d2a39314784526dc901367bdfb), with me trying to read some chaps from merged source and Chapter 161 from MD at the end.

**Comment by CarlosEsco** [comment]
Has nothing to do with hotlinking.  Mangalife is blocking tachi and neko at this time.

**Comment by CarlosEsco** [comment]
fixed in 2.2.2.2 with a harsh rate limiting.

**Comment by pre7736** [comment]
How to fix this?

**Comment by holysnipz** [comment]
> Has nothing to do with hotlinking

before i open this issue, i got caught in CF's anti-hotlink (error 1020) every single times. so, i just assume that. lol

> Mangalife is blocking tachi and neko at this time.

this might be it, since "now" i seems to be able to hotlink M4L's mangas fine on browser. yet Neko 2.2.2.2 still can't load.

**Comment by CarlosEsco** [comment]
can't fix at this time.  The owner said they would unblock tachi/neko once Dex is more stable.

**Comment by CarlosEsco** [comment]
It's been unblocked I'll need to lower the rate limit a little though it's pretty slow
